# Generated by Django 5.0.6 on 2024-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("title",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на видео"
            ),
        ),
    ]
